# Form implementation generated from reading ui file 'c:\Users\mrabh\OneDrive\Desktop\Pyqt\Main_Software\EntryGUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import (QCompleter, QLineEdit, QWidget, QApplication, QVBoxLayout, QTableWidget, QItemDelegate,
                             QHeaderView, QStyledItemDelegate, QTableWidgetItem, QMainWindow, QMessageBox, QPushButton)
from PyQt6.QtCore import Qt,QTimer, QTime,QThread, pyqtSignal, QDate, QDateTime
from PyQt6.QtGui import QFont, QPalette, QColor, QDoubleValidator
from All_function import all_function
from pdf_create import *
from DialogBox_alltype import *
import datetime
import speech_recognition as sr
import sqlite3
import icons_rc

class SpeechRecognitionThread(QThread):
    recognition_result = pyqtSignal(str)

    def __init__(self):
        super().__init__()
        self.recognizer = sr.Recognizer()

    def run(self):
        with sr.Microphone() as source:
            print("Speak Anything:")
            self.recognizer.pause_threshold = 0.8
            try:
                audio = self.recognizer.listen(source,  phrase_time_limit=3,timeout=3)
                text = self.recognizer.recognize_google(audio, language='en-IN')
                self.recognition_result.emit(text)
            except sr.WaitTimeoutError:
                self.recognition_result.emit("Timeout")
                print("Listening timed out while waiting for phrase to start")
            except sr.UnknownValueError:
                self.recognition_result.emit("Not Recognized")
                print("Sorry, could not recognize what you said")
            except sr.RequestError as e:
                self.recognition_result.emit("Error")
                print("Error occurred during speech recognition:", str(e))

class Ui_Entry_Window(object):
    def setupUi(self, Entry_Window):
        font = "Russo One"
        Entry_Window.setObjectName("Entry_Window")
        Entry_Window.resize(700, 769)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Entry_Window.sizePolicy().hasHeightForWidth())
        Entry_Window.setSizePolicy(sizePolicy)
        Entry_Window.setMaximumSize(QtCore.QSize(700, 800))
        Entry_Window.setStyleSheet("QLineEdit {\n"
"                background-color: #f3f3f3;\n"
"                border: 2px solid #c0c0c0;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                selection-background-color: #a8a8a8;\n"
"            }\n"
"\n"
"            QLineEdit:focus {\n"
"                border: 2px solid #707070;\n"
"                background-color: #ffffff;\n"
"            }\n"
"\n"
"QDialog{\n"
"    background-color: rgb(242,240,247);\n"
"}")
        self.gridLayout_4 = QtWidgets.QGridLayout(Entry_Window)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(parent=Entry_Window)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                      stop:0 #F7F7F7, stop:1 #E8E8E8);\n"
"    gridline-color: #DDDDDD;\n"
"    selection-background-color: #E6F1FF;\n"
"    selection-color: #333333;\n"
"\n"
"}\n"
"QTableWidget::item {\n"
"    text-align: center;\n"
"}\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                      stop:0 #4876AF, stop:1 #286090);\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    border-bottom: 1px solid #355F8C;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section:second {\n"
"    border-top-right-radius: 24px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #B3D7FF;\n"
"    color: #333333;\n"
"}\n"
"QTableWidget QHeaderView::section:pressed {\n"
"    background-color: #4F8BC9;\n"
"}\n"
"\n"
"\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #E6F1FF;\n"
"}")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.AnyKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.CurrentChanged|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.tableWidget, 2, 0, 1, 2)
        self.frame_4 = QtWidgets.QFrame(parent=Entry_Window)
        self.frame_4.setStyleSheet("QFrame {\n"
"    border: 2px solid #dddddd;\n"
"}\n"
"\n"
"\n"
"QLabel {\n"
"    font-family: Russo One;\n"
"    font-size: 18px;\n"
"    border : 0px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"                background-color: #f3f3f3;\n"
"                border: 2px solid #c0c0c0;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                selection-background-color: #a8a8a8;\n"
"                color:red;\n"
"                font-size: 14px;\n"
"            }\n"
"\n"
"            QLineEdit:focus {\n"
"                border: 2px solid #707070;\n"
"                background-color: #ffffff;\n"
"            }\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox_cash = QtWidgets.QComboBox(parent=self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Belanosima")
        font.setPointSize(-1)
        self.comboBox_cash.setFont(font)
        self.comboBox_cash.setStyleSheet("QComboBox {\n"
"    border-radius: 3px;\n"
"    padding: 5px;\n"
"    font-family: Belanosima;\n"
"    font-size: 18px;\n"
"    background-color: rgb(231, 255, 215);\n"
"}\n"
"")
        self.comboBox_cash.setObjectName("comboBox_cash")
        self.comboBox_cash.addItem("")
        self.comboBox_cash.addItem("")
        self.comboBox_cash.addItem("")
        self.comboBox_cash.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_cash, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 2, 1)
        self.giving_label = QtWidgets.QLabel(parent=self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Russo One")
        font.setPointSize(-1)
        self.giving_label.setFont(font)
        self.giving_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.giving_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.giving_label.setObjectName("giving_label")
        self.gridLayout_3.addWidget(self.giving_label, 0, 1, 1, 1)
        self.lineEdit_remaining = QtWidgets.QLineEdit(parent=self.frame_4)
        self.lineEdit_remaining.setReadOnly(True)
        self.lineEdit_remaining.setObjectName("lineEdit_remaining")
        self.gridLayout_3.addWidget(self.lineEdit_remaining, 1, 2, 1, 1)
        self.total_label = QtWidgets.QLabel(parent=self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Russo One")
        font.setPointSize(-1)
        self.total_label.setFont(font)
        self.total_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.total_label.setObjectName("total_label")
        self.gridLayout_3.addWidget(self.total_label, 0, 4, 2, 1)
        self.lineEdit_total = QtWidgets.QLineEdit(parent=self.frame_4)
        self.lineEdit_total.setReadOnly(True)
        self.lineEdit_total.setObjectName("lineEdit_total")
        self.gridLayout_3.addWidget(self.lineEdit_total, 0, 5, 2, 1)
        self.method_label = QtWidgets.QLabel(parent=self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Russo One")
        font.setPointSize(-1)
        self.method_label.setFont(font)
        self.method_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.method_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.method_label.setObjectName("method_label")
        self.gridLayout_3.addWidget(self.method_label, 0, 0, 1, 1)
        self.remaining_label = QtWidgets.QLabel(parent=self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Russo One")
        font.setPointSize(-1)
        self.remaining_label.setFont(font)
        self.remaining_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.remaining_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.remaining_label.setObjectName("remaining_label")
        self.gridLayout_3.addWidget(self.remaining_label, 1, 1, 1, 1)
        self.lineEdit_giving = QtWidgets.QLineEdit(parent=self.frame_4)
        self.lineEdit_giving.setDragEnabled(False)
        self.lineEdit_giving.setReadOnly(True)
        self.lineEdit_giving.setObjectName("lineEdit_giving")
        self.gridLayout_3.addWidget(self.lineEdit_giving, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame_4, 3, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(parent=Entry_Window)
        self.frame_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_2.setStyleSheet("QToolButton {\n"
"    border: none;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.name_label = QtWidgets.QLabel(parent=self.frame_2)
        self.name_label.setMaximumSize(QtCore.QSize(51, 41))
        font = QtGui.QFont()
        font.setFamily("Belanosima")
        self.name_label.setFont(font)
        self.name_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.name_label.setStyleSheet("")
        self.name_label.setText("")
        self.name_label.setPixmap(QtGui.QPixmap(":/icons/icons8-admin-40.png"))
        self.name_label.setScaledContents(True)
        self.name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)
        self.address_label = QtWidgets.QLabel(parent=self.frame_2)
        self.address_label.setMaximumSize(QtCore.QSize(51, 41))
        font = QtGui.QFont()
        font.setFamily("Belanosima")
        self.address_label.setFont(font)
        self.address_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.address_label.setStyleSheet("")
        self.address_label.setText("")
        self.address_label.setPixmap(QtGui.QPixmap(":/icons/location-pin.png"))
        self.address_label.setScaledContents(True)
        self.address_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.address_label.setObjectName("address_label")
        self.gridLayout.addWidget(self.address_label, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setInputMask("")
        self.lineEdit_name.setText("")
        self.lineEdit_name.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_2.addWidget(self.lineEdit_name)
        self.toolButton_name_micro = QtWidgets.QToolButton(parent=self.frame_2)
        self.toolButton_name_micro.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/microphone-black-shape.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_name_micro.setIcon(icon)
        self.toolButton_name_micro.setObjectName("toolButton_name_micro")
        self.horizontalLayout_2.addWidget(self.toolButton_name_micro)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 3)
        self.phone_label = QtWidgets.QLabel(parent=self.frame_2)
        self.phone_label.setMaximumSize(QtCore.QSize(51, 41))
        font = QtGui.QFont()
        font.setFamily("Belanosima")
        self.phone_label.setFont(font)
        self.phone_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.phone_label.setStyleSheet("")
        self.phone_label.setText("")
        self.phone_label.setPixmap(QtGui.QPixmap(":/icons/icons8-phone-100.png"))
        self.phone_label.setScaledContents(True)
        self.phone_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.phone_label.setObjectName("phone_label")
        self.gridLayout.addWidget(self.phone_label, 2, 0, 1, 1)
        self.lineEdit_phone = QtWidgets.QLineEdit(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_phone.setFont(font)
        self.lineEdit_phone.setText("")
        self.lineEdit_phone.setReadOnly(False)
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.gridLayout.addWidget(self.lineEdit_phone, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_address = QtWidgets.QLineEdit(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_address.setFont(font)
        self.lineEdit_address.setInputMask("")
        self.lineEdit_address.setText("")
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.horizontalLayout_3.addWidget(self.lineEdit_address)
        self.toolButton_addr_micro = QtWidgets.QToolButton(parent=self.frame_2)
        self.toolButton_addr_micro.setText("")
        self.toolButton_addr_micro.setIcon(icon)
        self.toolButton_addr_micro.setObjectName("toolButton_addr_micro")
        self.horizontalLayout_3.addWidget(self.toolButton_addr_micro)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 3)
        self.id_label = QtWidgets.QLabel(parent=self.frame_2)
        self.id_label.setMaximumSize(QtCore.QSize(51, 41))
        self.id_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.id_label.setStyleSheet("")
        self.id_label.setText("")
        self.id_label.setPixmap(QtGui.QPixmap(":/icons/icons8-id-80.png"))
        self.id_label.setScaledContents(True)
        self.id_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.id_label.setObjectName("id_label")
        self.gridLayout.addWidget(self.id_label, 2, 2, 1, 1)
        self.lineEdit_id = QtWidgets.QLineEdit(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_id.setFont(font)
        self.lineEdit_id.setText("")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.gridLayout.addWidget(self.lineEdit_id, 2, 3, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=Entry_Window)
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color: #D2E9E9;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_label = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Russo One")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.main_label.setFont(font)
        self.main_label.setObjectName("main_label")
        self.horizontalLayout.addWidget(self.main_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.date_label = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Russo One")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.date_label.setFont(font)
        self.date_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.date_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.date_label.setObjectName("date_label")
        self.verticalLayout.addWidget(self.date_label)
        self.time_label = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Russo One")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.time_label.setFont(font)
        self.time_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.time_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.verticalLayout.addWidget(self.time_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_4.addWidget(self.frame_3, 0, 0, 1, 2)
        self.frame = QtWidgets.QFrame(parent=Entry_Window)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.frame)
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"  background-color: rgb(213, 202, 255);\n"
"  border: 1px solid #dcdcdc;\n"
"  border-radius: 4px;\n"
"  selection-background-color: rgb(215, 192, 255);\n"
"  selection-color: #333333;\n"
"  font-size: 16px;\n"
"  color: #333333;\n"
"}\n"
"")
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 0, 0, 1, 1)
        self.checkBox_return = QtWidgets.QCheckBox(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_return.setFont(font)
        self.checkBox_return.setObjectName("checkBox_return")
        self.gridLayout_2.addWidget(self.checkBox_return, 0, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.lineEdit_comment = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_comment.setFont(font)
        self.lineEdit_comment.setStyleSheet("QLineEdit{\n"
"margin-bottom: 3px;\n"
"}")
        self.lineEdit_comment.setText("")
        self.lineEdit_comment.setObjectName("lineEdit_comment")
        self.gridLayout_2.addWidget(self.lineEdit_comment, 3, 0, 1, 4)
        self.note_label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Russo One")
        self.note_label.setFont(font)
        self.note_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.note_label.setStyleSheet("QLabel {\n"
"color: red;\n"
"}")
        self.note_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.note_label.setObjectName("note_label")
        self.gridLayout_2.addWidget(self.note_label, 2, 0, 1, 4)
        self.pushButton_telegram = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_telegram.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_telegram.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons8-telegram-480.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_telegram.setIcon(icon1)
        self.pushButton_telegram.setObjectName("pushButton_telegram")
        self.gridLayout_2.addWidget(self.pushButton_telegram, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(parent=Entry_Window)
        self.frame_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(29,94,255);\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"color: white;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    font-family: \"Arial\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: skyblue;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: dodgerblue;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.pushButton_submit = QtWidgets.QPushButton(parent=self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_submit.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons8-submit-60.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_submit.setIcon(icon2)
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.horizontalLayout_6.addWidget(self.pushButton_submit)
        self.pushButton_print = QtWidgets.QPushButton(parent=self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_print.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons8-print-64.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_print.setIcon(icon3)
        self.pushButton_print.setObjectName("pushButton_print")
        self.horizontalLayout_6.addWidget(self.pushButton_print)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gridLayout_4.addWidget(self.frame_5, 4, 0, 1, 2)

        self.retranslateUi(Entry_Window)
        QtCore.QMetaObject.connectSlotsByName(Entry_Window)
        Entry_Window.setTabOrder(self.lineEdit_name, self.lineEdit_address)
        Entry_Window.setTabOrder(self.lineEdit_address, self.lineEdit_phone)
        Entry_Window.setTabOrder(self.lineEdit_phone, self.lineEdit_id)
        Entry_Window.setTabOrder(self.lineEdit_id, self.tableWidget)
        Entry_Window.setTabOrder(self.tableWidget, self.lineEdit_giving)
        Entry_Window.setTabOrder(self.lineEdit_giving, self.comboBox_cash)
        Entry_Window.setTabOrder(self.comboBox_cash, self.pushButton_submit)
        Entry_Window.setTabOrder(self.pushButton_submit, self.pushButton_print)
        Entry_Window.setTabOrder(self.pushButton_print, self.lineEdit_remaining)
        Entry_Window.setTabOrder(self.lineEdit_remaining, self.lineEdit_total)

    def retranslateUi(self, Entry_Window):
        _translate = QtCore.QCoreApplication.translate
        Entry_Window.setWindowTitle(_translate("Entry_Window", "Entry"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Entry_Window", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Entry_Window", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Entry_Window", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Entry_Window", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Entry_Window", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Entry_Window", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Entry_Window", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Entry_Window", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Entry_Window", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Entry_Window", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Entry_Window", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Entry_Window", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Entry_Window", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Entry_Window", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Entry_Window", "15"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Entry_Window", "Description"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Entry_Window", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Entry_Window", "Rate"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Entry_Window", "Value"))
        self.comboBox_cash.setItemText(0, _translate("Entry_Window", "Cash"))
        self.comboBox_cash.setItemText(1, _translate("Entry_Window", "Udhar/Jma"))
        self.comboBox_cash.setItemText(2, _translate("Entry_Window", "UPI"))
        self.comboBox_cash.setItemText(3, _translate("Entry_Window", "Cheque"))
        self.giving_label.setText(_translate("Entry_Window", "Pay:"))
        self.total_label.setText(_translate("Entry_Window", "Total"))
        self.method_label.setText(_translate("Entry_Window", "Method"))
        self.remaining_label.setText(_translate("Entry_Window", "Remaining:"))
        self.lineEdit_name.setPlaceholderText(_translate("Entry_Window", "Name"))
        self.lineEdit_phone.setPlaceholderText(_translate("Entry_Window", "Phone No."))
        self.lineEdit_address.setPlaceholderText(_translate("Entry_Window", "Address"))
        self.lineEdit_id.setPlaceholderText(_translate("Entry_Window", "ID"))
        self.main_label.setText(_translate("Entry_Window", "Mahendra Traders"))
        self.date_label.setText(_translate("Entry_Window", "10-09-2023"))
        self.time_label.setText(_translate("Entry_Window", "10:45"))
        self.checkBox_return.setText(_translate("Entry_Window", "Return"))
        self.lineEdit_comment.setPlaceholderText(_translate("Entry_Window", "Comments"))
        self.note_label.setText(_translate("Entry_Window", "Note"))
        self.pushButton_submit.setText(_translate("Entry_Window", "Submit"))
        self.pushButton_print.setText(_translate("Entry_Window", "Print"))
# -----------------------------Main editing-------------------------#


#         #Microphone button
        screen_height = QApplication.primaryScreen().availableGeometry().height() - 30
        Entry_Window.resize(800, screen_height)
        self.recognition_thread = None
        self.toolButton_name_micro.clicked.connect(lambda: self.start_recognition(self.lineEdit_name, self.toolButton_name_micro))
        self.toolButton_addr_micro.clicked.connect(lambda: self.start_recognition(self.lineEdit_address, self.toolButton_addr_micro))
#         # self.recognizer = sr.Recognizer()
#         # self.edit_entry("23070835","08-07-2023","6:11:46 PM")
#     #Speech recognition  
    def closeEvent(self, event):
        if self.recognition_thread is not None and self.recognition_thread.isRunning():
            self.recognition_thread.quit()
            self.recognition_thread.wait()
        event.accept()

    def start_recognition(self,lineEdit, button):
        if self.recognition_thread is not None and self.recognition_thread.isRunning():
            return

        # button.setEnabled(False)
        self.toolButton_addr_micro.setEnabled(False)
        self.toolButton_name_micro.setEnabled(False)
        lineEdit.clear()
        lineEdit.setPlaceholderText("Listening...")
        self.recognition_thread = SpeechRecognitionThread()
        handle_result = lambda result: self.handle_recognition_result(result, lineEdit, button)
        self.recognition_thread.recognition_result.connect(handle_result)
        self.recognition_thread.finished.connect(self.cleanup_recognition_thread)
        self.recognition_thread.start()

    def handle_recognition_result(self, text, lineEdit, button):
        # button.setEnabled(True)
        self.toolButton_addr_micro.setEnabled(True)
        self.toolButton_name_micro.setEnabled(True)
        if text != "Error":
            if text != "Not Recognized":
                if text != "Timeout":
                    lineEdit.setText(text)
                else:
                    lineEdit.setPlaceholderText("Timeout")
            else:
                lineEdit.setPlaceholderText("Not Recognized")
        else:
            lineEdit.setPlaceholderText("Error occurred")

    def cleanup_recognition_thread(self):
        self.recognition_thread = None
    
    
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Entry_Window = QtWidgets.QDialog()
#     ui = Ui_Entry_Window()
#     ui.setupUi(Entry_Window)
#     Entry_Window.show()
#     sys.exit(app.exec())
